// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScheduledScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScheduledScan'](arg1, arg2, arg3);
}

export function CreateTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTarget'](arg1, arg2, arg3);
}

export function DeleteScheduledScan(arg1) {
  return window['go']['main']['App']['DeleteScheduledScan'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['main']['App']['DeleteTarget'](arg1);
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function GenerateReport(arg1) {
  return window['go']['main']['App']['GenerateReport'](arg1);
}

export function GetAuditLogs(arg1) {
  return window['go']['main']['App']['GetAuditLogs'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetScan(arg1) {
  return window['go']['main']['App']['GetScan'](arg1);
}

export function GetVulnerabilities(arg1) {
  return window['go']['main']['App']['GetVulnerabilities'](arg1);
}

export function LaunchScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchScan'](arg1, arg2, arg3);
}

export function ListScans() {
  return window['go']['main']['App']['ListScans']();
}

export function ListScheduledScans() {
  return window['go']['main']['App']['ListScheduledScans']();
}

export function ListTargets() {
  return window['go']['main']['App']['ListTargets']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function ToggleScheduledScan(arg1) {
  return window['go']['main']['App']['ToggleScheduledScan'](arg1);
}

export function ToggleTarget(arg1) {
  return window['go']['main']['App']['ToggleTarget'](arg1);
}
