// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScheduledScan(arg1:number,arg2:string,arg3:string):Promise<Record<string, any>>;

export function CreateTarget(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DeleteScheduledScan(arg1:number):Promise<Record<string, any>>;

export function DeleteTarget(arg1:number):Promise<Record<string, any>>;

export function ExportCSV(arg1:number):Promise<Record<string, any>>;

export function GenerateReport(arg1:number):Promise<Record<string, any>>;

export function GetAuditLogs(arg1:number):Promise<Record<string, any>>;

export function GetCurrentUser():Promise<Record<string, any>>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetScan(arg1:number):Promise<Record<string, any>>;

export function GetVulnerabilities(arg1:number):Promise<Record<string, any>>;

export function LaunchScan(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ListScans():Promise<Record<string, any>>;

export function ListScheduledScans():Promise<Record<string, any>>;

export function ListTargets():Promise<Record<string, any>>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<Record<string, any>>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function StartScan(arg1:number,arg2:string):Promise<Record<string, any>>;

export function ToggleScheduledScan(arg1:number):Promise<Record<string, any>>;

export function ToggleTarget(arg1:number):Promise<Record<string, any>>;
